services:
  hrm.db:
    container_name: hrm.db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=testhrm@0812
    restart: always
    ports:
      - "1633:1433"
    volumes:
      - ./.containers/db:/var/opt/mssql/data

  hrm.api:
    container_name: hrm.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=hrm.db,1433;Database=HRMDb;User Id=sa;Password=testhrm@0812;Encrypt=False;TrustServerCertificate=True
    ports:
      - "8880:8080"
      - "8881:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - hrm.db

  hrm.ui:
    container_name: hrm.ui
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiSettings__BaseUrl=http://hrm.api:8080
    ports:
      - "8989:80"
    depends_on:
      - hrm.api

